- name: example nginx website
  hosts: web
  tasks:
    - name: Start etcd
      service: name=etcd.service state=started
      sudo: yes
      sudo_user: root

    - name: Install docker-py
      pip: name=docker-py version=1.2.3 executable=/home/core/bin/pip

    - name: launch nginx container
      docker:
        image: nginx:1.7.1
        name: example-nginx
        ports:
          - "8080:80"
        state: started
